version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestSIQAPro1309Project
  gitServerName: prabhakaribm
  gitUrl: https://github.com/prabhakaribm
  gitUsername: prabhakaribm
  gitBranch: main
